### ISSUE TITLE
regex matching does not work on linux

### ISSUE THREAD

**Issue by whatchamccallum** [zachanassian/tu_optimize#16]
./tu_optimize wm Gauntlet -r climb 10
: Invalid hash characterck: /^GT\d\d$/
: Invalid hash character

with regex I know that $ means end of line. I tried just removing the $ but that didn't cut it. Any quick ideas? I'm going through read.cpp to see if I can figure anything out from there.

**Comment by whatchamccallum** [comment]
we are passing /^GT\d\d$/ as list_string

 47     boost::regex rx ("/(.*)/");
 48     boost::smatch sm;
 49     boost::regex_match (list_string,sm,rx);

the regex isn't matching for some reason. sm[1] is empty

**Comment by whatchamccallum** [comment]
Need some help

If I print list_string with something like
std:cout << "output:" << list_string << "END" << std:endl;
The output is
ENDput:/^GT\d\d$/

If I add 
list_string = "/^GT\d\d$/";
just before line 47 it works.

**Comment by zachanassian** [comment]
Can't test because I do not run linux.

Could be an encoding problem of the string. 

Could you try <code>/tu_optimize wm "/^GT\d\d$/" -r climb 10</code>

from the command line directly.

Also the result of

before line 47: list_string2 = "/^GT\d\d$/";
strcmp(list_string, list_string2) would be interesting. There must be a difference if one version works and the other does not. At the end might be useful to compare both strings on byte level...

**Comment by whatchamccallum** [comment]
Issue had to do with the version of boost libraries used. compiled on ubuntu 13.10 with the version provided through apt-get and the regex works just fine.
