### ISSUE TITLE
Razogoth Mutant-3 and Razogoth Mutant-5

### ISSUE THREAD

**Issue by ctenden** [zachanassian/tu_optimize#34]
I did a sim with:
Nexor, Demi Constrictor, Auger Bore, Arch Nova Elite, Xeno Suzerain(2),Steel Maiden,Sculpted Aegis

-r -o climb 20000

against Razogoth Mutant-1 and got a 86.43% win
against Razogoth Mutant-2 and got a 38.34% win
against Razogoth Mutant-3 and got a 59% win
against Razogoth Mutant-4 and got a 12.8% win
against Razogoth Mutant-5 and got a 41.6% win
against Razogoth Mutant and got a 5.76% win

The numbers don't seem to jive for Mutant 3 and Mutant 5

Thanks

**Comment by zachanassian** [comment]
Razogoth Mutant-1 to -6 are just the cards upgraded to level 1 or 6. They do not correspond to any Mission Level. Due to the definition of the mutant cards your results are possible. Unlike normal TU cards the mutant card at Level n is not always better then Mutant card at Level n-1 which explains the result you posted above.
You might also read [this](http://www.kongregate.com/forums/338/topics/390807?page=14#posts-8082862)
