### ISSUE TITLE
Error with climbing duplicate cards

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [zachanassian/tu_optimize#40]
The climb command doesn't behave as expected if you try to climb with a card both in your deck and in your collection. For example:
- Place Bolt Crag in your ownedcards.txt
- tu_optimize "Constantine-6,Bolt Crag" "/^GT12Sk\d\d$/"  climb 100000

Evaluated 1 decks (100000 + 0 simulations).
Optimized Deck: 0.00425: Constantine, Bolt Crag
- tu_optimize "Constantine-6,Bolt Crag-5" "/^GT12Sk\d\d$/"  climb 100000

Evaluated 3 decks (300000 + 300000 simulations).
Optimized Deck: 4.39858: Constantine, Bolt Crag-5, Bolt Crag

**Comment by zachanassian** [comment]
The cards specified in mydeck are implicitly add to your ownedcards if they do not exist in ownedcards. Not very intuitiv but that is how it works. That's why it is recommended to put all your cards in ownedcards and only use a subset in your deck.

First example tries climb with ownedcards (Constantine, Bolt Crag) => valid result "Constantine, Bolt Crag"

Second example tries climb with with ownedcards (Constantine, Bolt Cag-5, Bolt Crag) => valid result "Constantine, Bolt Crag-5, Bolt Crag"

HTH

**Comment by Karel-van-de-Plassche** [comment]
That explains a lot of weird bugs in my code. Thanks!
